//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        public int id { get; set; }
        public string numero { get; set; }
        public int cvv { get; set; }
        public int mes_exp { get; set; }
        public int ano_exp { get; set; }
        public bool selecionado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
