//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Subcategoria = new HashSet<Subcategoria>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<Subcategoria> Subcategoria { get; set; }
    }
}
