//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Endereco = new HashSet<Endereco>();
            this.Cartao = new HashSet<Cartao>();
            this.Venda = new HashSet<Venda>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public System.DateTime dt_nasc { get; set; }
        public bool sexo { get; set; }
        public string cpf { get; set; }
        public string cel { get; set; }
        public string sessao_api_pagSeguro { get; set; }
    
        public virtual ICollection<Endereco> Endereco { get; set; }
        public virtual ICollection<Cartao> Cartao { get; set; }
        public virtual ICollection<Venda> Venda { get; set; }
    }
}
