//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_winkEntities : DbContext
    {
        public DB_winkEntities()
            : base("name=DB_winkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> ClienteDefinir { get; set; }
        public DbSet<Endereco> EnderecoDefinir { get; set; }
        public DbSet<Cartao> CartaoDefinir { get; set; }
        public DbSet<Venda> VendaDefinir { get; set; }
        public DbSet<Categoria> CategoriaDefinir { get; set; }
        public DbSet<Subcategoria> SubcategoriaDefinir { get; set; }
        public DbSet<Produto> ProdutoDefinir { get; set; }
        public DbSet<Fornecedor> FornecedorDefinir { get; set; }
        public DbSet<Produto_Venda> Produto_VendaDefinir { get; set; }
        public DbSet<Oferta> OfertaDefinir { get; set; }
        public DbSet<Produto_oferta> Produto_ofertaDefinir { get; set; }
        public DbSet<Administrador> AdministradorDefinir { get; set; }
        public DbSet<Relatorio> RelatorioDefinir { get; set; }
    }
}
