//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public Fornecedor()
        {
            this.Produto = new HashSet<Produto>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string cnpj { get; set; }
    
        public virtual ICollection<Produto> Produto { get; set; }
    }
}
