//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        public Oferta()
        {
            this.Entidade1 = new HashSet<Produto_oferta>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public System.DateTime validade { get; set; }
        public bool expirado { get; set; }
        public string valor_oferta { get; set; }
    
        public virtual ICollection<Produto_oferta> Entidade1 { get; set; }
    }
}
