//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.Produto_Venda = new HashSet<Produto_Venda>();
            this.Entidade1 = new HashSet<Produto_oferta>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public decimal valor { get; set; }
        public int qtde_estoque { get; set; }
        public double desconto_promocao { get; set; }
        public System.Data.Spatial.DbGeography foto { get; set; }
        public bool promocao { get; set; }
    
        public virtual Subcategoria Subcategoria { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual ICollection<Produto_Venda> Produto_Venda { get; set; }
        public virtual ICollection<Produto_oferta> Entidade1 { get; set; }
    }
}
