//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relatorio
    {
        public int id { get; set; }
        public int tipo { get; set; }
        public System.DateTime dt_inicio { get; set; }
        public System.DateTime dt_fim { get; set; }
    }
}
