//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public Venda()
        {
            this.Produto_Venda = new HashSet<Produto_Venda>();
        }
    
        public int id { get; set; }
        public System.DateTime dt_venda { get; set; }
        public double valor_total { get; set; }
        public int status { get; set; }
        public string cod_transacao { get; set; }
        public string link_pgto { get; set; }
        public int forma_pgto { get; set; }
        public string hash_venda { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Produto_Venda> Produto_Venda { get; set; }
    }
}
