//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        public int Id { get; set; }
        public string numero { get; set; }
        public int cvv { get; set; }
        public int mesExp { get; set; }
        public int anoExp { get; set; }
        public bool selecionado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
