//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conta()
        {
            this.Movimentacao = new HashSet<Movimentacao>();
        }
    
        public int Id { get; set; }
        public long Numero { get; set; }
        public double Saldo { get; set; }
        public TipoConta TipoConta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimentacao> Movimentacao { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
