//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_wink.com.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DM_WinkContainer : DbContext
    {
        public DM_WinkContainer()
            : base("name=DM_WinkContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Endereco> Enderecos { get; set; }
        public virtual DbSet<Cartao> Cartaoes { get; set; }
        public virtual DbSet<Venda> Vendas { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Subcategoria> Subcategorias { get; set; }
        public virtual DbSet<Fornecedor> Fornecedores { get; set; }
        public virtual DbSet<Produto> Produtos { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
        public virtual DbSet<ProdutoOferta> ProdutosOfertas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<ProdutoVenda> ProdutosVendas { get; set; }
    }
}
