//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        public int Id { get; set; }
        public double Valor { get; set; }
        public System.DateTime Data { get; set; }
        public TipoMovimento TipoMovimento { get; set; }
        public double Saldo { get; set; }
    
        public virtual Conta Conta { get; set; }
    }
}
