//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.ProdutoOferta = new HashSet<ProdutoOferta>();
            this.ProdutoVenda = new HashSet<ProdutoVenda>();
        }
    
        public int Id { get; set; }
        public string nome { get; set; }
        public int valor { get; set; }
        public int qtdEstoque { get; set; }
        public double descontoPromocao { get; set; }
        public string foto { get; set; }
        public double promocao { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoOferta> ProdutoOferta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoVenda> ProdutoVenda { get; set; }
    }
}
