//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_wink.com.Models
{
    using System;
    
    public enum TipoMovimento : int
    {
        SAQUE = 1,
        DEPOSITO = 2,
        TRANSFERENCIA = 3
    }
}
