//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_wink.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venda()
        {
            this.ProdutoVenda = new HashSet<ProdutoVenda>();
        }
    
        public int Id { get; set; }
        public System.DateTime dtVenda { get; set; }
        public double valorVenda { get; set; }
        public int status { get; set; }
        public string codTransacao { get; set; }
        public string linkPgto { get; set; }
        public int formaPgto { get; set; }
        public string hashVenda { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoVenda> ProdutoVenda { get; set; }
    }
}
